entropyxyz/cli

README.md
- updated readme wirth dislcaimer explaining alpha stage for js cli
=> [NayNay] Readme Change

README.md
Adds basic support section to project readme.
=> Adds basic support section to project readme.

src/flows/manage-accounts/new-key.ts
- we are removing the ability to encrypt data saved to the config for now
Closes #52
=> [NayNay] Removed ability to encrypt data

package.json, yarn.lock
- updated rc version and cleaned up package json scripts for linking local sdk
=> [NayNay] Updating rc version for sdk

src/flows/UserPrograms/index.ts, src/flows/sign/index.ts, src/index.ts
=> [NayNay] Exit to main menu action

src/flows/manage-accounts/import-key.ts
- updated import functionality to not ask users the type of string they are importing
closes #61
=> [NayNay] Removing seed clarification

src/flows/balance/index.ts
=> [NayNay] Capitilize bits

package.json, yarn.lock
=> [NayNay] New sdk version

README.md
=> [NayNay] Adding node version to readme

src/flows/manage-accounts/index.ts
=> [NayNay] Reformat accounts when listed

src/flows/balance/index.ts
Closes #87 
`Address 5CqJyjALDFz4sKjQgK8NXBQGHCWAiV63xXn2Dye393Y6Vghz has a balance of: 999,998,999,999,113,121,747 BITS`
=> [NayNay] Big Number formatting

package.json, src/config/index.ts, yarn.lock
- there was an issue with a new dependency added in a recent commit
=> [NayNay] Revert changes made to config

package.json, yarn.lock
Fixes https://github.com/entropyxyz/cli/issues/119
=> replace start script with build + global install

README.md, package.json
This PR:
- :heavy_check_mark: fixes conflicts in between `dev` + `main`
- :heavy_check_mark: improves/ clarifies the README (there were conflicts, so I fixed those and also improved)
=> merge main

src/config/index.ts, src/flows/manage-accounts/helpers/import-key.ts, src/flows/manage-accounts/index.ts, src/flows/manage-accounts/list.ts, src/flows/manage-accounts/new-key.ts, src/types/index.ts, tests/manage-accounts.test.ts, tests/testing-utils/constants.ts
- created new method to handle listing accounts as a pure function
- added unit tests for new method
- confirmed manage accounts still works as expected with new method
closes #122
=> [NayNay] Account List Update + Testing

src/config/migrations/01.ts, src/config/migrations/index.ts, tests/testing-utils/index.ts
Designed to supercede https://github.com/entropyxyz/cli/pull/136
=> migration: move default endpoint

src/common/masking.ts, src/flows/sign/index.ts
- updated signing to pull in the correct endpoint to be used
- removed a noisy log to the console
=> [NayNay] Fix Signing

CHANGELOG.md, package.json
=> [RELEASE] v0.0.2

CHANGELOG.md, package.json
=> [NayNay] Sync main with dev

CHANGELOG.md, package.json
=> v0.0.3 🔥 HOT FIX

README.md
Clarifies `feature_branch -> dev -> main` PR process.
=> Clarify PR branch process.

CHANGELOG.md, package.json, yarn.lock
=> [NayNay] update sdk v0.2.3

dev/bin/test-hosts.sh
- Resolves #276 
- previously getent was used to derive the host names and ips from the hosts file
- getent is a linux only command, so the test always failed on my mac machine
- updated to use grep instead
=> [NayNay] Fix tests-hosts for all machines

package.json, src/account/main.ts, tests/faucet.test.ts, yarn.lock
This updates the cli to the new sdk version: `@entropyxyz/sdk@0.4.0`
=> + @entropyxyz/sdk@0.4.0

CHANGELOG.md, src/account/interaction.ts, src/common/constants.ts
- Resolves #273
- Resolves #235 
- updated register to fail without exiting out of the tui
- also added some ansi colors to our logs, will update the rest of the logs in another PR if this is the road we would like to follow with console logs
=> [NayNay] Register Errors

src/faucet/interaction.ts, src/faucet/main.ts, src/faucet/utils.ts, tests/faucet.test.ts
- updated faucet constants to use new program mod key and program pointer deployed from boot script
=> [NayNay] Testnet Faucet

CHANGELOG.md, package.json
- 0.1.0
- Change 1
- Change 2
- ...
=> [NayNay] Minor Version Upgrade

CHANGELOG.md, src/common/ascii.ts, src/tui.ts
=> animated logo *swipe*

CHANGELOG.md, src/program/command.ts
=> cli-fix: `entropy program list` now writes output!

CHANGELOG.md, src/faucet/interaction.ts
- updated faucet amount shown to users to be displayed as whole BITS instead of nanoBITS/lilBITS
=> [NayNay] Faucet amount as BITS

src/account/utils.ts, src/balance/command.ts, src/balance/interaction.ts, src/common/load-entropy.ts, src/faucet/interaction.ts, src/transfer/command.ts, src/transfer/interaction.ts
found some bugs
- with calls to `getTokenDetails`
- faucet funding (`options` vs `opts`)
=> mixmix - fixes to naynay/any-balance
