entropyxyz/cli

src/common/initializeEntropy.ts
src/common/utils.ts

fix the math for time calculations
@johnnymatthews was seeing some time issues so was i so now i buffer the time stamp with time it takes to query and all th math is done in "native unix time stamp numbers" rather then trying to convert to seconds

milleseconds not seconds for time stamp

---

README.md

Addresses https://github.com/entropyxyz/entropy-docs/issues/90. Adds a simple callout to the top of the README:
> This tool is early development. As such, a lot of things do not work. Feel free to play around with it and report any issues at [github.com/entropyxyz/cli](https://github.com/entropyxyz/cli).

Adds a "This project in early development" warning to README.

---

src/common/ascii.ts

- leaving as hardcoded value for now, will look into a more dynamic approach to grabbing the version
Closes #84

[NayNay] Updating version of core in ascii art

---

README.md

Closes https://github.com/entropyxyz/cli/issues/19
This PR doesn't contain 
- troubleshooting steps yet, because we don't have any.
- contribution instructions, because the JS team are figuring out how to manage that. Don't wanna put words in their mouth.

Improves README for self-surface.

---

src/tui.ts

closes #141 
this was actually a "race condition" issue. `config.init` wasn't being awaited 
I tested this locally and now it works for me: as in i can start up entropy

i#141 non existing entropy dir

---

CHANGELOG.md
src/flows/index.ts
src/flows/user-program-management/add.ts
src/flows/user-program-management/helpers/questions.ts
src/flows/user-program-management/index.ts
src/flows/user-program-management/types.ts
tests/user-program-management.test.ts

- Resolves #152 
- updated folder structure for consistency
- added new method for adding programs as a pure function
- added tests

[NayNay] User Programs: Add Program + testing

---

CHANGELOG.md
src/common/masking.ts
src/flows/index.ts
src/flows/register/index.ts
src/flows/register/register.ts
src/flows/register/types.ts
src/tui.ts
tests/register.test.ts

- added new register pure function
- imported new types from sdk
- added unit test for default register
closes #149

[NayNay] Entropy Register + Unit Tests

---

CHANGELOG.md
src/flows/user-program-management/helpers/questions.ts
src/flows/user-program-management/index.ts
src/flows/user-program-management/remove.ts
src/flows/user-program-management/types.ts
tests/user-program-management.test.ts

- Resolves #154 
- added new service file for remove program pure function
- updated unit test file for user program management to reduce spin up and down of node
- added new test for removing programs

[NayNay] User Program Management::Remove a program + Testing

---

src/cli.ts
src/flows/balance/cli.ts

- Resolves #181
- updated programmatic interface for balance to return a string rather than the number returned from the pure function

[NayNay] Hotfix: Fixing balance in CLI

---

src/flows/register/register.ts
src/flows/register/types.ts
tests/register.test.ts

- mistakingly tested the wrong register method
- fixed it

[NayNay] Fixing register tests

---

tests/manage-accounts.test.ts
tests/testing-utils/setup-test.ts
tests/transfer.test.ts

remove un-needed sleep commands (SDK is smarter with its spinUpNetwork tool)

remove "sleep" calls as SDK utils handle those

---

src/cli.ts

- Updates the output of the CLI when using the `--help` argument:
```shell
Usage: entropy [options] [command]
CLI interface for interacting with entropy.xyz. Running this binary without any commands or arguments starts a text-based interface.
Options:
-e, --endpoint <endpoint> 
```
Closes https://github.com/entropyxyz/cli/issues/180

Clears up what the TUI is and how to start it.

---

src/config/index.ts

I noticed that there was a nice error-handler for `getSync` but not for `get`!
Consolidated!

get all config.get* methods fail safely

---

src/account/command.ts
src/cli.ts
src/common/utils-cli.ts
src/config/index.ts
src/sign/command.ts
src/transfer/command.ts
tests/config.test.ts

So yeah the config was not good.... this chills it out, makes them config functions way simpler, safer.

fix config (again)

---

src/account/command.ts
src/account/interaction.ts
src/account/main.ts
src/account/utils.ts

During QA discussion, notice that entropy register was coded the same in CLI + TUI.
This PR:
- reduces what `main` does to only be registering on-chain
- moves entropy config mutation + persistence into `util`
- changes `command` and `interaction` to use the same 2 functions
- includes refactor of the `command` action

refactor entropy register so CLI/TUI are similar

---

package.json
src/common/masking.ts
tests/common.test.ts
yarn.lock

improve masking fn

---

src/faucet/interaction.ts
src/faucet/utils.ts
tests/faucet.test.ts

- Resolves #233 
- udpated tests, wrote new test to test failed route for register but running into an issue with tape possibly, commented test out for now

[NayNay] Updating faucet amount

---

src/sign/interaction.ts
tests/sign.test.ts

- Resolves #222 
- updated signing error handling to return human readbale message when user tries to sign without registering first

[NayNay] Signing error messaging

---

.github/workflows/test.yaml
CHANGELOG.md
README.md
dev/bin/build.sh
package.json
src/cli.ts
src/common/ascii.ts
src/common/utils-cli.ts
src/types/index.ts

- Resolves #266 
- added option to display versions

[NayNay] Entropy Version

---

CHANGELOG.md
README.md
src/cli.ts
src/common/utils-cli.ts
src/program/command.ts
src/program/interaction.ts
src/program/main.ts
src/program/types.ts
src/tui.ts
tests/program.test.ts
yarn.lock

I was hitting some problems with options colliding between the root `entropy` command and the other sub-commands like `entropy account register`.
Reading the `commander` docs I saw there was an option for commands `{ default: true }`. This allows us to move tui functionality into a sub-command `entropy tui` AND sets this as the default command that is run (if no sub-command is called).
This resolves almost all the problems in https://github.com/entropyxyz/cli/issues/265 and means that we can have
- the same env for TUI and CLI
- no collision between the root command and subcommand options!

move tui to a (default) subcommand

---

src/account/interaction.ts
src/cli.ts
src/common/utils-cli.ts
src/common/utils.ts

- Resolves #244 
- contrary to intended use of the help option with commander, this PR adds handler when user adds help option after option that requires an argument
- for now, only updated account option, may require discussion with team if this is how we want to proceed

[NayNay] Help text for command options

---

.gitignore
src/account/command.ts
src/common/constants.ts
src/common/utils-cli.ts
src/common/utils.ts
src/tui.ts

- the general purpose of the custom config works, however there is alot of work to be done regarding error handling
- i have only started testing the custom config feature with a file that doesn't exist: ./custom-files/custom-config-<#>.json
- this originally caused issues on the tui and did not allow for anything to start until the tui eventually errored out
- similar errors were found with the cli as well
- ive fixed the tui for the most part
- but theres still lots to do to fix the cli in terms of proper error handling

[NayNay] Testing Mix's Custom Config

---

CHANGELOG.md
src/account/command.ts
src/account/interaction.ts
src/account/utils.ts

- Resolves #82
- updated account creation, new or imported, to return all the information a user will need to secure their account
- updated both tui and cli to return the same information

[NayNay] Return all info, similar to subkey

---

CHANGELOG.md
src/balance/command.ts
src/balance/interaction.ts
src/common/constants.ts
src/common/utils.ts
src/faucet/interaction.ts
src/transfer/command.ts
src/transfer/constants.ts
src/transfer/interaction.ts
src/transfer/main.ts
src/transfer/types.ts
src/types/index.ts
tests/faucet.test.ts
tests/testing-utils/constants.mjs
tests/transfer.test.ts

- Resolves #221 
- it had come to our attn that we were using the wrong units for the tokens display
- we were under the impression that bits were the smallest unit of the entropy token, that was a mistake
- updated all mentions of tokens and bits to match their respective definition
- updated return of balance to the human readable format, using BITS
- added new method to grab token details from chain
- needs changelog
- needs documentation update

[NayNay] Updating Units within Entropy

---

CHANGELOG.md
src/account/utils.ts
src/balance/main.ts
src/common/load-entropy.ts
src/common/substrate-utils.ts
src/common/utils.ts
src/faucet/main.ts
src/transfer/command.ts
src/transfer/interaction.ts
src/transfer/main.ts
src/tui.ts
tests/account.test.ts
tests/faucet.test.ts
tests/transfer.test.ts

- Resolves #328 
- updated trasnfer to only need substrate rather than the entire entropy instance

[NayNay] Only substrate
